spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      kduytran:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 #Number of requests that Gateway should monitor in CLOSE_STATE
        permitted-number-of-calls-in-half-open-state: 2 #Number of requests that Gateway should monitor in HALF_OPEN_STATE
        failure-rate-threshold: 50 #If at least 50% of requests are failed, it will change the STATE
        wait-duration-in-open-state: 10000 #Need to wait for 10000ms to OPEN_STATE -> HALF_OPEN_STATE
