spring:
  application:
    name: "accounts"

build:
  version: "1.0"

accounts:
  message: "Welcome to accounts microservice related production APIs "
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx