spring:
  application:
    name: "accounts"

build:
  version: "2.0"

accounts:
  message: "Welcome to accounts microservice related qa APIs "
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx
