build:
  version: "2.0"

cards:
  message: "Welcome to cards microservice related QA APIs"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx