spring:
  application:
    name: "cards"

build:
  version: "3.0"

cards:
  message: "Welcome to cards microservice related local APIs"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx