spring:
  application:
    name: "loans"

build:
  version: "3.0"

loans:
  message: "Welcome to loans microservice related local APIs"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx